openapi: 3.0.1
info:
  title: Joke Plugin
  description: A plugin that allows the user to get a random joke using ChatGPT. If you do not know the user's username, ask them first before making queries to the plugin. Otherwise, use the username "global".
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /jokes/{username}:
    get:
      operationId: getJoke
      summary: Get a random joke
      parameters:
      - in: path
        name: username
        schema:
            type: string
        required: true
        description: The name of the user.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getJokeResponse'

components:
  schemas:
    getJokeResponse:
      type: object
      properties:
        joke:
          type: string
          description: The joke text.
